spring:
  datasource:
    url: jdbc:h2:mem:filestoragedb
    username: sa
    password: 12345
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
